import { promises as fs } from 'fs';
import path from 'path';
import chokidar from 'chokidar';
import type { SummaryData, SyncConfig } from '@shared/types';

export class ObsidianSyncManager {
  private config: SyncConfig['obsidian'];
  private watcher: chokidar.FSWatcher | null = null;

  constructor(config: SyncConfig['obsidian']) {
    this.config = config;
  }

  // ===== Initialization =====

  async initialize(): Promise<boolean> {
    if (!this.config.enabled) return false;

    try {
      // Ensure vault path exists
      await fs.access(this.config.vaultPath);

      // Ensure note folder exists
      const notePath = path.join(this.config.vaultPath, this.config.noteFolder);
      await fs.mkdir(notePath, { recursive: true });

      // Start file watcher for two-way sync
      if (this.config.twoWaySync) {
        this.startWatcher();
      }

      return true;
    } catch (e) {
      console.error('Obsidian sync initialization failed:', e);
      return false;
    }
  }

  async dispose(): Promise<void> {
    await this.watcher?.close();
    this.watcher = null;
  }

  // ===== Save Operations =====

  async saveSummary(summary: SummaryData): Promise<string> {
    if (!this.config.enabled) {
      throw new Error('Obsidian sync disabled');
    }

    const filename = this.generateFilename(summary);
    const filepath = path.join(
      this.config.vaultPath,
      this.config.noteFolder,
      filename
    );

    const content = this.renderNote(summary);
    await this.atomicWrite(filepath, content);

    return filepath;
  }

  async saveBatch(summaries: SummaryData[]): Promise<string[]> {
    const paths: string[] = [];
    
    for (const summary of summaries) {
      try {
        const filepath = await this.saveSummary(summary);
        paths.push(filepath);
      } catch (e) {
        console.error(`Failed to save ${summary.url}:`, e);
      }
    }

    return paths;
  }

  // ===== Template Rendering =====

  private renderNote(summary: SummaryData): string {
    const template = this.config.template || this.getDefaultTemplate();
    
    return template
      .replace(/{{title}}/g, summary.title)
      .replace(/{{url}}/g, summary.url)
      .replace(/{{domain}}/g, summary.domain)
      .replace(/{{depth}}/g, String(summary.depth))
      .replace(/{{tags}}/g, summary.tags.join(', '))
      .replace(/{{timestamp}}/g, new Date(summary.timestamp).toISOString())
      .replace(/{{tokens}}/g, String(summary.tokenCount))
      .replace(/{{core}}/g, summary.summary.core)
      .replace(/{{keyPoints}}/g, summary.summary.keyPoints.map(p => `- ${p}`).join('\n'))
      .replace(/{{til}}/g, summary.summary.til.map(t => `- ${t}`).join('\n'))
      .replace(/{{actions}}/g, summary.summary.actions.map(a => `- [ ] ${a}`).join('\n'))
      .replace(/{{entities}}/g, summary.summary.entities.map(e => `- [[${e}]]`).join('\n'))
      .replace(/{{terms}}/g, summary.summary.terms.map(t => `- **${t.term}**: ${t.definition}`).join('\n'));
  }

  private getDefaultTemplate(): string {
    return `---
created: {{timestamp}}
url: {{url}}
title: {{title}}
domain: {{domain}}
depth: {{depth}}
tags: [{{tags}}]
tokens: {{tokens}}
---

# {{title}}

> **URL**: [{{url}}]({{url}})
> **Domain**: {{domain}} | **Depth**: {{depth}}/5

## Суть

{{core}}

## Ключевые тезисы

{{keyPoints}}

## TIL (Today I Learned)

{{til}}

## Действия

{{actions}}

## Сущности

{{entities}}

## Термины

{{terms}}

---
*Generated by pzdrk* [[pzdrk-index]]
`;
  }

  // ===== File Operations =====

  private generateFilename(summary: SummaryData): string {
    // Sanitize title for filename
    const sanitized = summary.title
      .replace(/[^a-zA-Z0-9\u0400-\u04FF\s-]/g, '')
      .replace(/\s+/g, '-')
      .slice(0, 50);
    
    const date = new Date(summary.timestamp).toISOString().split('T')[0];
    return `${date}-${sanitized}.md`;
  }

  private async atomicWrite(filepath: string, content: string): Promise<void> {
    const tempPath = `${filepath}.tmp`;
    await fs.writeFile(tempPath, content, 'utf-8');
    await fs.rename(tempPath, filepath);
  }

  // ===== Two-Way Sync =====

  private startWatcher(): void {
    const watchPath = path.join(this.config.vaultPath, this.config.noteFolder);
    
    this.watcher = chokidar.watch(watchPath, {
      ignored: /(^|[/\\])\../,
      persistent: true,
      ignoreInitial: true
    });

    this.watcher
      .on('add', (filepath) => this.handleFileChange('add', filepath))
      .on('change', (filepath) => this.handleFileChange('change', filepath))
      .on('unlink', (filepath) => this.handleFileChange('unlink', filepath));
  }

  private async handleFileChange(
    event: 'add' | 'change' | 'unlink',
    filepath: string
  ): Promise<void> {
    // Only process .md files
    if (!filepath.endsWith('.md')) return;

    // Check if it's a pzdrk note
    const content = await fs.readFile(filepath, 'utf-8').catch(() => '');
    if (!content.includes('Generated by pzdrk')) return;

    // Parse and sync back
    if (event === 'change' || event === 'add') {
      const summary = this.parseNote(content, filepath);
      if (summary) {
        // Emit event for upstream sync
        this.emitChange(summary);
      }
    }
  }

  private parseNote(content: string, filepath: string): Partial<SummaryData> | null {
    try {
      // Extract frontmatter
      const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
      const frontmatter: Record<string, string> = {};
      
      if (frontmatterMatch) {
        const lines = frontmatterMatch[1].split('\n');
        for (const line of lines) {
          const match = line.match(/^([^:]+):\s*(.+)$/);
          if (match) {
            frontmatter[match[1].trim()] = match[2].trim();
          }
        }
      }

      return {
        url: frontmatter.url || '',
        title: frontmatter.title || path.basename(filepath, '.md'),
        timestamp: new Date(frontmatter.created || Date.now()).getTime(),
        domain: frontmatter.domain || 'unknown',
        depth: parseInt(frontmatter.depth) || 3,
        tags: frontmatter.tags?.split(',').map(t => t.trim()) || [],
      };
    } catch (e) {
      return null;
    }
  }

  private emitChange(summary: Partial<SummaryData>): void {
    // This would integrate with the event bus
    console.log('Obsidian file changed:', summary.title);
  }

  // ===== Index Management =====

  async updateIndex(allSummaries: SummaryData[]): Promise<void> {
    const indexPath = path.join(
      this.config.vaultPath,
      this.config.noteFolder,
      'pzdrk-index.md'
    );

    // Group by date
    const byDate = new Map<string, SummaryData[]>();
    for (const s of allSummaries) {
      const date = new Date(s.timestamp).toISOString().split('T')[0];
      const group = byDate.get(date) || [];
      group.push(s);
      byDate.set(date, group);
    }

    // Generate index
    let indexContent = `# Pzdrk Index\n\n`;
    indexContent += `Total summaries: ${allSummaries.length}\n\n`;

    const sortedDates = Array.from(byDate.keys()).sort().reverse();
    for (const date of sortedDates) {
      indexContent += `## ${date}\n\n`;
      for (const s of byDate.get(date)!) {
        const filename = this.generateFilename(s);
        indexContent += `- [${s.title}](${filename}) - ${s.domain}\n`;
      }
      indexContent += '\n';
    }

    await this.atomicWrite(indexPath, indexContent);
  }

  // ===== Stats =====

  async getStats(): Promise<{ totalFiles: number; totalSize: number }> {
    const notePath = path.join(this.config.vaultPath, this.config.noteFolder);
    
    try {
      const files = await fs.readdir(notePath);
      const mdFiles = files.filter(f => f.endsWith('.md'));
      
      let totalSize = 0;
      for (const file of mdFiles) {
        const stat = await fs.stat(path.join(notePath, file));
        totalSize += stat.size;
      }

      return { totalFiles: mdFiles.length, totalSize };
    } catch (e) {
      return { totalFiles: 0, totalSize: 0 };
    }
  }
}
